apiVersion: v2
name: clammit
description: A Helm chart for https://github.com/ifad/clammit.
type: application
version: 0.0.0-develop
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: clamav
  repository: https://wiremind.github.io/wiremind-helm-charts
  version: 3.5.x
  condition: clamav.enabled
keywords:
  - ClamAV
  - Clammit
  - OpenG2P
annotations:
  catalog.cattle.io/display-name: "Clammit"
